export class ActionConstants {
    public static INITIALIZE_SUB_SEQUENCE_SEARCH_PAGE: string= "INITIALIZE_SUB_SEQUENCE_SEARCH_PAGE";
    public static SHOW_MODAL_DIALOG_SEARCH_REQUEST: string = "SHOW_MODAL_DIALOG_SEARCH_REQUEST";
    public static LOAD_SIMPLE_SUCCES: string = "LOAD_SIMPLE_SUCCES";
    //public static LOAD_SIMPLE: string = "LOAD_SIMPLE";
    public static INITIALIZE_DATABASE_SUB_SEQUENCE_SEARCH_PAGE : string = "INITIALIZE_DATABASE_SUB_SEQUENCE_SEARCH_PAGE";
    public static SHOW_MODAL_DIALOG_REMOVE_UNFILTERED: string = "SHOW_MODAL_DIALOG_REMOVE_UNFILTERED";
    public static SHOW_SNACKBAR_REMOVE_UNFILTERED: string = "SHOW_SNACKBAR_REMOVE_UNFILTERED";
    public static SHOW_MODAL_DIALOG_REMOVE_FILTERED: string = "SHOW_MODAL_DIALOG_REMOVE_FILTERED";
    public static SHOW_SNACKBAR_REMOVE_FILTERED: string = "SHOW_SNACKBAR_REMOVE_FILTERED";
    public static DOWNLOAD_UNFILTERED_FASTA : string = "DOWNLOAD_UNFILTERED_FASTA";
    public static DOWNLOAD_FILTERED_FASTA : string = "DOWNLOAD_FILTERED_FASTA";
    public static DOWNLOAD_UNFILTERED_IDS : string = "DOWNLOAD_UNFILTERED_IDS";
    public static DOWNLOAD_FILTERED_IDS : string = "DOWNLOAD_FILTERED_IDS";
    public static SHOW_MODAL_DIALOG_UPLOAD_EXCEL: string = "SHOW_MODAL_DIALOG_UPLOAD_EXCEL";
}