export class ActionConstants {
    public static INITIALIZE_SUB_SEQUENCE_SEARCH_PAGE: string= "INITIALIZE_SUB_SEQUENCE_SEARCH_PAGE";
    public static SHOW_MODAL_DIALOG_SEARCH_REQUEST: string = "SHOW_MODAL_DIALOG_SEARCH_REQUEST";
    public static LOAD_SIMPLE_SUCCES: string = "LOAD_SIMPLE_SUCCES";
    //public static LOAD_SIMPLE: string = "LOAD_SIMPLE";
    public static INITIALIZE_DATABASE_SUB_SEQUENCE_SEARCH_PAGE : string = "INITIALIZE_DATABASE_SUB_SEQUENCE_SEARCH_PAGE";
}